Add new Docker configuration

diff --git a/build/docker/files/zoonavigator-api/run.sh.template b/build/docker/files/zoonavigator-api/run.sh.template
--- a/build/docker/files/zoonavigator-api/run.sh.template
+++ b/build/docker/files/zoonavigator-api/run.sh.template
@@ -6,18 +6,6 @@ rm -f ./RUNNING_PID
 # Generate random app secret if not defined
 export SECRET_KEY=${SECRET_KEY:-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9~!@#$%^&*_-' | fold -w 64 | head -n 1)}
 
-# Generate and update front-end config
-mkdir public
-
-dockerize \
-  -template ./config.json.template:./public/config.json
-
-ASSETS_JAR=$(ls lib | grep -E "com.elkozmon.zoonavigator-play-(.*?)-assets.jar")
-
-jar uf \
-  lib/${ASSETS_JAR} \
-  public/config.json
-
 # Config
 ZOOKEEPER_34="true"
 ZOOKEEPER_34_JAR="zookeeper-3.4.11.jar"
@@ -38,7 +26,6 @@ JAVA_OPTS="$JAVA_OPTS \
 [ -n "$SSL_KEYSTORE_PASSWORD" ] && JAVA_OPTS="$JAVA_OPTS -J-Dplay.server.https.keyStore.password=$SSL_KEYSTORE_PASSWORD"
 [ -n "$SSL_KEYSTORE_TYPE" ] && JAVA_OPTS="$JAVA_OPTS -J-Dplay.server.https.keyStore.type=$SSL_KEYSTORE_TYPE"
 [ -n "$SECRET_KEY" ] && JAVA_OPTS="$JAVA_OPTS -J-Dplay.http.secret.key=$SECRET_KEY"
-[ -n "$SESSION_TIMEOUT_MILLIS" ] && JAVA_OPTS="$JAVA_OPTS -J-Dplay.http.session.maxAge=$SESSION_TIMEOUT_MILLIS"
 
 [ -n "$JAVA_XMS" ] && JAVA_OPTS="$JAVA_OPTS -J-Xms$JAVA_XMS"
 [ -n "$JAVA_XMX" ] && JAVA_OPTS="$JAVA_OPTS -J-Xmx$JAVA_XMX"
@@ -76,6 +63,12 @@ then
 else
   cp lib/$ZOOKEEPER_35_JAR lib/$ZOOKEEPER_JAR
 fi
+
+# Exit if command fails
+set -e
+
+# Generate application config
+./conf/zoonavigator.conf.sh >> ./conf/application.conf
 
 # Start application
 exec ./bin/zoonavigator-play ${JAVA_OPTS}
